### ISSUE TITLE
Need models with 2x scale

### ISSUE THREAD

**Issue by EMJian** [Lqm26/BMCNet-ESR#3]
Great work! Could you release more BMCNet_***_x2 models about three datasets.

**Comment by Lqm26** [comment]
I'm sorry, but due to a recent restructuring of our model, the previous weights are no longer compatible and the model will need to be retrained. However, I'm currently quite busy and don't have time to train the 2X model at the moment. You can proceed with the training following our instructions. Thank you for your understanding.
